minVersion: 0.23.1
changelogPolicy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
targets:
  - name: npm
  - name: brew
    tap: Tabishahmad/tools
    template: >
      require 'language/node'

      class SentryWizard < Formula
        desc "The Libapm Wizard helps you set up your projects with Sentry"
        homepage "https://github.com/Tabishahmad/libapm-wizard"
        url "https://registry.npmjs.org/@libapm1/wizard/-/wizard-{{version}}.tgz"
        sha256 "{{checksums.ibapm1-wizard-v__VERSION____tgz}}"
        version "{{version}}"
        license "MIT"

        depends_on "node"

        def install
          system "npm", "install", *Language::Node.std_npm_install_args(libexec)
          bin.install_symlink Dir["#{libexec}/bin/*"]
        end
        test do
          assert_match version.to_s, shell_output("#{bin}/sentry-wizard --version").chomp
        end
      end
  - name: registry
    apps:
      app:sentry-wizard:
        urlTemplate: https://github.com/Tabishahmad/libapm-wizard/releases/tag/V{{version}}
  - name: github
    tagPrefix: v
